version: '3.7'

services:
  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - target: 9090
        published: 9090
        protocol: tcp
    volumes:
      # chown -R nobody:nogroup prometheus-data/
      - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /srv/volumes/docker/prometheus-data:/prometheus
    container_name: prometheus-docker
  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    volumes:
      # chown -R 472:472 grafana-data/
      - /srv/volumes/docker/grafana-data:/var/lib/grafana
    container_name: grafana-docker
  blackbox-exporter:
    image: prom/blackbox-exporter
    restart: unless-stopped
    container_name: prometheus-blackbox
    ports:
      - target: 9115
        published: 9115
        protocol: tcp
    volumes:
      - /etc/prometheus/blackbox.yml:/config/blackbox.yml
  stne:
    image: stne:latest
    restart: unless-stopped
    command: --port 9516 #--servers 21975 4468
    ports:
      - "9516:9516"
    container_name: speedtest-exporter
